config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :debts
  resources :credits
  resources :statuses
  resources :reservations
  resources :people
  resources :companies
  resources :documents
  resources :rooms
  resources :rates_schedules
  resources :rates_categories
  resources :rates
  resources :rooms_categories
  resources :cities
  resources :states
  resources :countries

   root 'pages#home'

   get 'signup'  => 'users#new'
   resources :users

   get 'login'  => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/debt.rb
class Debt < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :document
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/rate.rb
class Rate < ActiveRecord::Base
end

app/models/rates_schedule.rb
class RatesSchedule < ActiveRecord::Base
  belongs_to :rate
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :company
  belongs_to :person
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :rooms_category
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/rates_schedules_controller.rb
class RatesSchedulesController < ApplicationController
  before_action :set_rates_schedule, only: [:show, :edit, :update, :destroy]

  # GET /rates_schedules
  # GET /rates_schedules.json
  def index
    @rates_schedules = RatesSchedule.all
  end

  # GET /rates_schedules/1
  # GET /rates_schedules/1.json
  def show
  end

  # GET /rates_schedules/new
  def new
    @rates_schedule = RatesSchedule.new
  end

  # GET /rates_schedules/1/edit
  def edit
  end

  # POST /rates_schedules
  # POST /rates_schedules.json
  def create
    @rates_schedule = RatesSchedule.new(rates_schedule_params)

    respond_to do |format|
      if @rates_schedule.save
        format.html { redirect_to @rates_schedule, notice: 'Rates schedule was successfully created.' }
        format.json { render :show, status: :created, location: @rates_schedule }
      else
        format.html { render :new }
        format.json { render json: @rates_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates_schedules/1
  # PATCH/PUT /rates_schedules/1.json
  def update
    respond_to do |format|
      if @rates_schedule.update(rates_schedule_params)
        format.html { redirect_to @rates_schedule, notice: 'Rates schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rates_schedule }
      else
        format.html { render :edit }
        format.json { render json: @rates_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates_schedules/1
  # DELETE /rates_schedules/1.json
  def destroy
    @rates_schedule.destroy
    respond_to do |format|
      format.html { redirect_to rates_schedules_url, notice: 'Rates schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rates_schedule
      @rates_schedule = RatesSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rates_schedule_params
      params.require(:rates_schedule).permit(:from, :to, :rate_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rates_schedules_helper.rb
module RatesSchedulesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rates_schedules/_form.html.erb
<%= form_for(@rates_schedule) do |f| %>
  <% if @rates_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rates_schedule.errors.count, "error") %> prohibited this rates_schedule from being saved:</h2>

      <ul>
      <% @rates_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br>
    <%= f.date_select :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.date_select :to %>
  </div>
  <div class="field">
    <%= f.label :rate_id %><br>
    <%= f.text_field :rate_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates_schedules/edit.html.erb
<h1>Editing Rates Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rates_schedule %> |
<%= link_to 'Back', rates_schedules_path %>

app/views/rates_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rates Schedules</h1>

<table>
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rates_schedules.each do |rates_schedule| %>
      <tr>
        <td><%= rates_schedule.from %></td>
        <td><%= rates_schedule.to %></td>
        <td><%= rates_schedule.rate %></td>
        <td><%= link_to 'Show', rates_schedule %></td>
        <td><%= link_to 'Edit', edit_rates_schedule_path(rates_schedule) %></td>
        <td><%= link_to 'Destroy', rates_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rates schedule', new_rates_schedule_path %>

app/views/rates_schedules/new.html.erb
<h1>New Rates Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', rates_schedules_path %>

app/views/rates_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @rates_schedule.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @rates_schedule.to %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @rates_schedule.rate %>
</p>

<%= link_to 'Edit', edit_rates_schedule_path(@rates_schedule) %> |
<%= link_to 'Back', rates_schedules_path %>