config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :debts
  resources :credits
  resources :statuses
  resources :reservations
  resources :people
  resources :companies
  resources :documents
  resources :rooms
  resources :rates_schedules
  resources :rates_categories
  resources :rates
  resources :rooms_categories
  resources :cities
  resources :states
  resources :countries

   root 'pages#home'

   get 'signup'  => 'users#new'
   resources :users

   get 'login'  => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/debt.rb
class Debt < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :document
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/rate.rb
class Rate < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :company
  belongs_to :person
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :rooms_category
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/_header.html.erb
<% if current_user %>
  <div class="header col-md-12">
    <nav class="container">
      <i class="col-md-1"><%= link_to '', root_path, class: 'glyphicon glyphicon-home', title: 'Home'%></i>
      <div class="col-md-7">
        <div class="options col-md-2">
          <div class="dropdown-toggle pull-left" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Tarifas<span class="caret"></span>
          </div>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to 'Categorias de Tarifa', rates_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Valores x Tarifas', rates_categories_path %></li>
            <li><%= link_to 'Tarifário', rates_schedules_path %></li>
          </ul>
        </div>
        <div class="options col-md-2">
          <div class="dropdown-toggle pull-left" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Cadastros<span class="caret"></span>
          </div>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to 'Acomodações Categorias', rooms_categories_path %></li>
            <li><%= link_to 'Acomodações', rooms_path %></li>
          </ul>
        </div>
      </div>
      <div class="session col-md-4 pull-right">
        <span class="pull-left"><%= current_user.email %></span>
        <i><%= link_to "logout", logout_path, method: "delete", class: 'glyphicon glyphicon-log-out', title: 'Logout' %></i>
      </div>
    </nav>
  </div>
<% end %>