config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :debts
  resources :credits
  resources :statuses
  resources :reservations
  resources :people
  resources :companies
  resources :documents
  resources :rooms
  resources :rates_schedules
  resources :rates_categories
  resources :rates
  resources :rooms_categories
  resources :cities
  resources :states
  resources :countries

   root 'pages#home'

   get 'signup'  => 'users#new'
   resources :users

   get 'login'  => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/debt.rb
class Debt < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :document
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/rate.rb
class Rate < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :company
  belongs_to :person
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :rooms_category
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>