config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :debts
  resources :credits
  resources :statuses
  resources :reservations
  resources :people
  resources :companies
  resources :documents
  resources :rooms
  resources :rates_schedules
  resources :rates_categories
  resources :rates
  resources :rooms_categories
  resources :cities
  resources :states
  resources :countries

   root 'pages#home'

   get 'signup'  => 'users#new'
   resources :users

   get 'login'  => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
end

app/models/debt.rb
class Debt < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :document
  belongs_to :country
  belongs_to :state
  belongs_to :city
end

app/models/rate.rb
class Rate < ActiveRecord::Base
end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :company
  belongs_to :person
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :rooms_category
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]

  # GET /credits
  # GET /credits.json
  def index
    @credits = Credit.all
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
  end

  # GET /credits/new
  def new
    @credit = Credit.new
  end

  # GET /credits/1/edit
  def edit
  end

  # POST /credits
  # POST /credits.json
  def create
    @credit = Credit.new(credit_params)

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
        format.json { render :show, status: :created, location: @credit }
      else
        format.html { render :new }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credits/1
  # PATCH/PUT /credits/1.json
  def update
    respond_to do |format|
      if @credit.update(credit_params)
        format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit }
      else
        format.html { render :edit }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credits/1
  # DELETE /credits/1.json
  def destroy
    @credit.destroy
    respond_to do |format|
      format.html { redirect_to credits_url, notice: 'Credit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit
      @credit = Credit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_params
      params.require(:credit).permit(:name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credits/_form.html.erb
<%= form_for(@credit) do |f| %>
  <% if @credit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>

      <ul>
      <% @credit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credits/edit.html.erb
<h1>Editing Credit</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Back', credits_path %>

app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Credits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.name %></td>
        <td><%= link_to 'Show', credit %></td>
        <td><%= link_to 'Edit', edit_credit_path(credit) %></td>
        <td><%= link_to 'Destroy', credit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit', new_credit_path %>

app/views/credits/new.html.erb
<h1>New Credit</h1>

<%= render 'form' %>

<%= link_to 'Back', credits_path %>

app/views/credits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @credit.name %>
</p>

<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>